#!/usr/bin/env python3
"""
Flask server for scholar data API.

Serves scholar JSON files generated by the cron job. Containerized with Docker.
"""

import os

from src.logging_config import setup_logging
from src.serve import app

# So WARNING logs (e.g. 401 reasons, Crossref failures) appear in Docker logs
setup_logging(level=os.environ.get("LOG_LEVEL", "INFO"))

if __name__ == "__main__":
    host = os.environ.get("FLASK_HOST", "0.0.0.0")
    port = int(os.environ.get("FLASK_PORT", "5000"))
    debug = os.environ.get("FLASK_DEBUG", "false").lower() == "true"
    app.run(host=host, port=port, debug=debug)
